# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/procamora/Documents/Gestor-Series/app/utils/../../app/views/ui/acerca_de.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(557, 372)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Iconos/Icons/fatcow/Principal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_info = QtWidgets.QLabel(self.widget)
        self.label_info.setText("")
        self.label_info.setObjectName("label_info")
        self.horizontalLayout.addWidget(self.label_info)
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.tab)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_imagen = QtWidgets.QLabel(self.widget_2)
        self.label_imagen.setText("")
        self.label_imagen.setObjectName("label_imagen")
        self.gridLayout_2.addWidget(self.label_imagen, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 623, 12319))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_licencia = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_licencia.setObjectName("label_licencia")
        self.gridLayout_5.addWidget(self.label_licencia, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.pushButtonClose = QtWidgets.QPushButton(Dialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Iconos/Icons/fatcow/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonClose.setIcon(icon1)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.gridLayout.addWidget(self.pushButtonClose, 1, 0, 1, 1, QtCore.Qt.AlignRight)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Info"))
        self.label_licencia.setText(_translate("Dialog", "GNU GENERAL PUBLIC LICENSE\n"
"                                                            Version 3, 29 June 2007\n"
"\n"
"                                                            Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>\n"
"                                                            Everyone is permitted to copy and distribute verbatim copies\n"
"                                                            of this license document, but changing it is not allowed.\n"
"\n"
"                                                            Preamble\n"
"\n"
"                                                            The GNU General Public License is a free, copyleft license\n"
"                                                            for\n"
"                                                            software and other kinds of works.\n"
"\n"
"                                                            The licenses for most software and other practical works are\n"
"                                                            designed\n"
"                                                            to take away your freedom to share and change the works. By\n"
"                                                            contrast,\n"
"                                                            the GNU General Public License is intended to guarantee your\n"
"                                                            freedom to\n"
"                                                            share and change all versions of a program--to make sure it\n"
"                                                            remains free\n"
"                                                            software for all its users. We, the Free Software\n"
"                                                            Foundation, use the\n"
"                                                            GNU General Public License for most of our software; it\n"
"                                                            applies also to\n"
"                                                            any other work released this way by its authors. You can\n"
"                                                            apply it to\n"
"                                                            your programs, too.\n"
"\n"
"                                                            When we speak of free software, we are referring to freedom,\n"
"                                                            not\n"
"                                                            price. Our General Public Licenses are designed to make sure\n"
"                                                            that you\n"
"                                                            have the freedom to distribute copies of free software (and\n"
"                                                            charge for\n"
"                                                            them if you wish), that you receive source code or can get\n"
"                                                            it if you\n"
"                                                            want it, that you can change the software or use pieces of\n"
"                                                            it in new\n"
"                                                            free programs, and that you know you can do these things.\n"
"\n"
"                                                            To protect your rights, we need to prevent others from\n"
"                                                            denying you\n"
"                                                            these rights or asking you to surrender the rights.\n"
"                                                            Therefore, you have\n"
"                                                            certain responsibilities if you distribute copies of the\n"
"                                                            software, or if\n"
"                                                            you modify it: responsibilities to respect the freedom of\n"
"                                                            others.\n"
"\n"
"                                                            For example, if you distribute copies of such a program,\n"
"                                                            whether\n"
"                                                            gratis or for a fee, you must pass on to the recipients the\n"
"                                                            same\n"
"                                                            freedoms that you received. You must make sure that they,\n"
"                                                            too, receive\n"
"                                                            or can get the source code. And you must show them these\n"
"                                                            terms so they\n"
"                                                            know their rights.\n"
"\n"
"                                                            Developers that use the GNU GPL protect your rights with two\n"
"                                                            steps:\n"
"                                                            (1) assert copyright on the software, and (2) offer you this\n"
"                                                            License\n"
"                                                            giving you legal permission to copy, distribute and/or\n"
"                                                            modify it.\n"
"\n"
"                                                            For the developers\' and authors\' protection, the GPL clearly\n"
"                                                            explains\n"
"                                                            that there is no warranty for this free software. For both\n"
"                                                            users\' and\n"
"                                                            authors\' sake, the GPL requires that modified versions be\n"
"                                                            marked as\n"
"                                                            changed, so that their problems will not be attributed\n"
"                                                            erroneously to\n"
"                                                            authors of previous versions.\n"
"\n"
"                                                            Some devices are designed to deny users access to install or\n"
"                                                            run\n"
"                                                            modified versions of the software inside them, although the\n"
"                                                            manufacturer\n"
"                                                            can do so. This is fundamentally incompatible with the aim\n"
"                                                            of\n"
"                                                            protecting users\' freedom to change the software. The\n"
"                                                            systematic\n"
"                                                            pattern of such abuse occurs in the area of products for\n"
"                                                            individuals to\n"
"                                                            use, which is precisely where it is most unacceptable.\n"
"                                                            Therefore, we\n"
"                                                            have designed this version of the GPL to prohibit the\n"
"                                                            practice for those\n"
"                                                            products. If such problems arise substantially in other\n"
"                                                            domains, we\n"
"                                                            stand ready to extend this provision to those domains in\n"
"                                                            future versions\n"
"                                                            of the GPL, as needed to protect the freedom of users.\n"
"\n"
"                                                            Finally, every program is threatened constantly by software\n"
"                                                            patents.\n"
"                                                            States should not allow patents to restrict development and\n"
"                                                            use of\n"
"                                                            software on general-purpose computers, but in those that do,\n"
"                                                            we wish to\n"
"                                                            avoid the special danger that patents applied to a free\n"
"                                                            program could\n"
"                                                            make it effectively proprietary. To prevent this, the GPL\n"
"                                                            assures that\n"
"                                                            patents cannot be used to render the program non-free.\n"
"\n"
"                                                            The precise terms and conditions for copying, distribution\n"
"                                                            and\n"
"                                                            modification follow.\n"
"\n"
"                                                            TERMS AND CONDITIONS\n"
"\n"
"                                                            0. Definitions.\n"
"\n"
"                                                            \"This License\" refers to version 3 of the GNU\n"
"                                                            General Public License.\n"
"\n"
"                                                            \"Copyright\" also means copyright-like laws that\n"
"                                                            apply to other kinds of\n"
"                                                            works, such as semiconductor masks.\n"
"\n"
"                                                            \"The Program\" refers to any copyrightable work\n"
"                                                            licensed under this\n"
"                                                            License. Each licensee is addressed as \"you\".\n"
"                                                            \"Licensees\" and\n"
"                                                            \"recipients\" may be individuals or organizations.\n"
"\n"
"                                                            To \"modify\" a work means to copy from or adapt all\n"
"                                                            or part of the work\n"
"                                                            in a fashion requiring copyright permission, other than the\n"
"                                                            making of an\n"
"                                                            exact copy. The resulting work is called a \"modified\n"
"                                                            version\" of the\n"
"                                                            earlier work or a work \"based on\" the earlier\n"
"                                                            work.\n"
"\n"
"                                                            A \"covered work\" means either the unmodified\n"
"                                                            Program or a work based\n"
"                                                            on the Program.\n"
"\n"
"                                                            To \"propagate\" a work means to do anything with it\n"
"                                                            that, without\n"
"                                                            permission, would make you directly or secondarily liable\n"
"                                                            for\n"
"                                                            infringement under applicable copyright law, except\n"
"                                                            executing it on a\n"
"                                                            computer or modifying a private copy. Propagation includes\n"
"                                                            copying,\n"
"                                                            distribution (with or without modification), making\n"
"                                                            available to the\n"
"                                                            public, and in some countries other activities as well.\n"
"\n"
"                                                            To \"convey\" a work means any kind of propagation\n"
"                                                            that enables other\n"
"                                                            parties to make or receive copies. Mere interaction with a\n"
"                                                            user through\n"
"                                                            a computer network, with no transfer of a copy, is not\n"
"                                                            conveying.\n"
"\n"
"                                                            An interactive user interface displays \"Appropriate\n"
"                                                            Legal Notices\"\n"
"                                                            to the extent that it includes a convenient and prominently\n"
"                                                            visible\n"
"                                                            feature that (1) displays an appropriate copyright notice,\n"
"                                                            and (2)\n"
"                                                            tells the user that there is no warranty for the work\n"
"                                                            (except to the\n"
"                                                            extent that warranties are provided), that licensees may\n"
"                                                            convey the\n"
"                                                            work under this License, and how to view a copy of this\n"
"                                                            License. If\n"
"                                                            the interface presents a list of user commands or options,\n"
"                                                            such as a\n"
"                                                            menu, a prominent item in the list meets this criterion.\n"
"\n"
"                                                            1. Source Code.\n"
"\n"
"                                                            The \"source code\" for a work means the preferred\n"
"                                                            form of the work\n"
"                                                            for making modifications to it. \"Object code\"\n"
"                                                            means any non-source\n"
"                                                            form of a work.\n"
"\n"
"                                                            A \"Standard Interface\" means an interface that\n"
"                                                            either is an official\n"
"                                                            standard defined by a recognized standards body, or, in the\n"
"                                                            case of\n"
"                                                            interfaces specified for a particular programming language,\n"
"                                                            one that\n"
"                                                            is widely used among developers working in that language.\n"
"\n"
"                                                            The \"System Libraries\" of an executable work\n"
"                                                            include anything, other\n"
"                                                            than the work as a whole, that (a) is included in the normal\n"
"                                                            form of\n"
"                                                            packaging a Major Component, but which is not part of that\n"
"                                                            Major\n"
"                                                            Component, and (b) serves only to enable use of the work\n"
"                                                            with that\n"
"                                                            Major Component, or to implement a Standard Interface for\n"
"                                                            which an\n"
"                                                            implementation is available to the public in source code\n"
"                                                            form. A\n"
"                                                            \"Major Component\", in this context, means a major\n"
"                                                            essential component\n"
"                                                            (kernel, window system, and so on) of the specific operating\n"
"                                                            system\n"
"                                                            (if any) on which the executable work runs, or a compiler\n"
"                                                            used to\n"
"                                                            produce the work, or an object code interpreter used to run\n"
"                                                            it.\n"
"\n"
"                                                            The \"Corresponding Source\" for a work in object\n"
"                                                            code form means all\n"
"                                                            the source code needed to generate, install, and (for an\n"
"                                                            executable\n"
"                                                            work) run the object code and to modify the work, including\n"
"                                                            scripts to\n"
"                                                            control those activities. However, it does not include the\n"
"                                                            work\'s\n"
"                                                            System Libraries, or general-purpose tools or generally\n"
"                                                            available free\n"
"                                                            programs which are used unmodified in performing those\n"
"                                                            activities but\n"
"                                                            which are not part of the work. For example, Corresponding\n"
"                                                            Source\n"
"                                                            includes interface definition files associated with source\n"
"                                                            files for\n"
"                                                            the work, and the source code for shared libraries and\n"
"                                                            dynamically\n"
"                                                            linked subprograms that the work is specifically designed to\n"
"                                                            require,\n"
"                                                            such as by intimate data communication or control flow\n"
"                                                            between those\n"
"                                                            subprograms and other parts of the work.\n"
"\n"
"                                                            The Corresponding Source need not include anything that\n"
"                                                            users\n"
"                                                            can regenerate automatically from other parts of the\n"
"                                                            Corresponding\n"
"                                                            Source.\n"
"\n"
"                                                            The Corresponding Source for a work in source code form is\n"
"                                                            that\n"
"                                                            same work.\n"
"\n"
"                                                            2. Basic Permissions.\n"
"\n"
"                                                            All rights granted under this License are granted for the\n"
"                                                            term of\n"
"                                                            copyright on the Program, and are irrevocable provided the\n"
"                                                            stated\n"
"                                                            conditions are met. This License explicitly affirms your\n"
"                                                            unlimited\n"
"                                                            permission to run the unmodified Program. The output from\n"
"                                                            running a\n"
"                                                            covered work is covered by this License only if the output,\n"
"                                                            given its\n"
"                                                            content, constitutes a covered work. This License\n"
"                                                            acknowledges your\n"
"                                                            rights of fair use or other equivalent, as provided by\n"
"                                                            copyright law.\n"
"\n"
"                                                            You may make, run and propagate covered works that you do\n"
"                                                            not\n"
"                                                            convey, without conditions so long as your license otherwise\n"
"                                                            remains\n"
"                                                            in force. You may convey covered works to others for the\n"
"                                                            sole purpose\n"
"                                                            of having them make modifications exclusively for you, or\n"
"                                                            provide you\n"
"                                                            with facilities for running those works, provided that you\n"
"                                                            comply with\n"
"                                                            the terms of this License in conveying all material for\n"
"                                                            which you do\n"
"                                                            not control copyright. Those thus making or running the\n"
"                                                            covered works\n"
"                                                            for you must do so exclusively on your behalf, under your\n"
"                                                            direction\n"
"                                                            and control, on terms that prohibit them from making any\n"
"                                                            copies of\n"
"                                                            your copyrighted material outside their relationship with\n"
"                                                            you.\n"
"\n"
"                                                            Conveying under any other circumstances is permitted solely\n"
"                                                            under\n"
"                                                            the conditions stated below. Sublicensing is not allowed;\n"
"                                                            section 10\n"
"                                                            makes it unnecessary.\n"
"\n"
"                                                            3. Protecting Users\' Legal Rights From Anti-Circumvention\n"
"                                                            Law.\n"
"\n"
"                                                            No covered work shall be deemed part of an effective\n"
"                                                            technological\n"
"                                                            measure under any applicable law fulfilling obligations\n"
"                                                            under article\n"
"                                                            11 of the WIPO copyright treaty adopted on 20 December 1996,\n"
"                                                            or\n"
"                                                            similar laws prohibiting or restricting circumvention of\n"
"                                                            such\n"
"                                                            measures.\n"
"\n"
"                                                            When you convey a covered work, you waive any legal power to\n"
"                                                            forbid\n"
"                                                            circumvention of technological measures to the extent such\n"
"                                                            circumvention\n"
"                                                            is effected by exercising rights under this License with\n"
"                                                            respect to\n"
"                                                            the covered work, and you disclaim any intention to limit\n"
"                                                            operation or\n"
"                                                            modification of the work as a means of enforcing, against\n"
"                                                            the work\'s\n"
"                                                            users, your or third parties\' legal rights to forbid\n"
"                                                            circumvention of\n"
"                                                            technological measures.\n"
"\n"
"                                                            4. Conveying Verbatim Copies.\n"
"\n"
"                                                            You may convey verbatim copies of the Program\'s source code\n"
"                                                            as you\n"
"                                                            receive it, in any medium, provided that you conspicuously\n"
"                                                            and\n"
"                                                            appropriately publish on each copy an appropriate copyright\n"
"                                                            notice;\n"
"                                                            keep intact all notices stating that this License and any\n"
"                                                            non-permissive terms added in accord with section 7 apply to\n"
"                                                            the code;\n"
"                                                            keep intact all notices of the absence of any warranty; and\n"
"                                                            give all\n"
"                                                            recipients a copy of this License along with the Program.\n"
"\n"
"                                                            You may charge any price or no price for each copy that you\n"
"                                                            convey,\n"
"                                                            and you may offer support or warranty protection for a fee.\n"
"\n"
"                                                            5. Conveying Modified Source Versions.\n"
"\n"
"                                                            You may convey a work based on the Program, or the\n"
"                                                            modifications to\n"
"                                                            produce it from the Program, in the form of source code\n"
"                                                            under the\n"
"                                                            terms of section 4, provided that you also meet all of these\n"
"                                                            conditions:\n"
"\n"
"                                                            a) The work must carry prominent notices stating that you\n"
"                                                            modified\n"
"                                                            it, and giving a relevant date.\n"
"\n"
"                                                            b) The work must carry prominent notices stating that it is\n"
"                                                            released under this License and any conditions added under\n"
"                                                            section\n"
"                                                            7. This requirement modifies the requirement in section 4 to\n"
"                                                            \"keep intact all notices\".\n"
"\n"
"                                                            c) You must license the entire work, as a whole, under this\n"
"                                                            License to anyone who comes into possession of a copy. This\n"
"                                                            License will therefore apply, along with any applicable\n"
"                                                            section 7\n"
"                                                            additional terms, to the whole of the work, and all its\n"
"                                                            parts,\n"
"                                                            regardless of how they are packaged. This License gives no\n"
"                                                            permission to license the work in any other way, but it does\n"
"                                                            not\n"
"                                                            invalidate such permission if you have separately received\n"
"                                                            it.\n"
"\n"
"                                                            d) If the work has interactive user interfaces, each must\n"
"                                                            display\n"
"                                                            Appropriate Legal Notices; however, if the Program has\n"
"                                                            interactive\n"
"                                                            interfaces that do not display Appropriate Legal Notices,\n"
"                                                            your\n"
"                                                            work need not make them do so.\n"
"\n"
"                                                            A compilation of a covered work with other separate and\n"
"                                                            independent\n"
"                                                            works, which are not by their nature extensions of the\n"
"                                                            covered work,\n"
"                                                            and which are not combined with it such as to form a larger\n"
"                                                            program,\n"
"                                                            in or on a volume of a storage or distribution medium, is\n"
"                                                            called an\n"
"                                                            \"aggregate\" if the compilation and its resulting\n"
"                                                            copyright are not\n"
"                                                            used to limit the access or legal rights of the\n"
"                                                            compilation\'s users\n"
"                                                            beyond what the individual works permit. Inclusion of a\n"
"                                                            covered work\n"
"                                                            in an aggregate does not cause this License to apply to the\n"
"                                                            other\n"
"                                                            parts of the aggregate.\n"
"\n"
"                                                            6. Conveying Non-Source Forms.\n"
"\n"
"                                                            You may convey a covered work in object code form under the\n"
"                                                            terms\n"
"                                                            of sections 4 and 5, provided that you also convey the\n"
"                                                            machine-readable Corresponding Source under the terms of\n"
"                                                            this License,\n"
"                                                            in one of these ways:\n"
"\n"
"                                                            a) Convey the object code in, or embodied in, a physical\n"
"                                                            product\n"
"                                                            (including a physical distribution medium), accompanied by\n"
"                                                            the\n"
"                                                            Corresponding Source fixed on a durable physical medium\n"
"                                                            customarily used for software interchange.\n"
"\n"
"                                                            b) Convey the object code in, or embodied in, a physical\n"
"                                                            product\n"
"                                                            (including a physical distribution medium), accompanied by a\n"
"                                                            written offer, valid for at least three years and valid for\n"
"                                                            as\n"
"                                                            long as you offer spare parts or customer support for that\n"
"                                                            product\n"
"                                                            model, to give anyone who possesses the object code either\n"
"                                                            (1) a\n"
"                                                            copy of the Corresponding Source for all the software in the\n"
"                                                            product that is covered by this License, on a durable\n"
"                                                            physical\n"
"                                                            medium customarily used for software interchange, for a\n"
"                                                            price no\n"
"                                                            more than your reasonable cost of physically performing this\n"
"                                                            conveying of source, or (2) access to copy the\n"
"                                                            Corresponding Source from a network server at no charge.\n"
"\n"
"                                                            c) Convey individual copies of the object code with a copy\n"
"                                                            of the\n"
"                                                            written offer to provide the Corresponding Source. This\n"
"                                                            alternative is allowed only occasionally and\n"
"                                                            noncommercially, and\n"
"                                                            only if you received the object code with such an offer, in\n"
"                                                            accord\n"
"                                                            with subsection 6b.\n"
"\n"
"                                                            d) Convey the object code by offering access from a\n"
"                                                            designated\n"
"                                                            place (gratis or for a charge), and offer equivalent access\n"
"                                                            to the\n"
"                                                            Corresponding Source in the same way through the same place\n"
"                                                            at no\n"
"                                                            further charge. You need not require recipients to copy the\n"
"                                                            Corresponding Source along with the object code. If the\n"
"                                                            place to\n"
"                                                            copy the object code is a network server, the Corresponding\n"
"                                                            Source\n"
"                                                            may be on a different server (operated by you or a third\n"
"                                                            party)\n"
"                                                            that supports equivalent copying facilities, provided you\n"
"                                                            maintain\n"
"                                                            clear directions next to the object code saying where to\n"
"                                                            find the\n"
"                                                            Corresponding Source. Regardless of what server hosts the\n"
"                                                            Corresponding Source, you remain obligated to ensure that it\n"
"                                                            is\n"
"                                                            available for as long as needed to satisfy these\n"
"                                                            requirements.\n"
"\n"
"                                                            e) Convey the object code using peer-to-peer transmission,\n"
"                                                            provided\n"
"                                                            you inform other peers where the object code and\n"
"                                                            Corresponding\n"
"                                                            Source of the work are being offered to the general public\n"
"                                                            at no\n"
"                                                            charge under subsection 6d.\n"
"\n"
"                                                            A separable portion of the object code, whose source code is\n"
"                                                            excluded\n"
"                                                            from the Corresponding Source as a System Library, need not\n"
"                                                            be\n"
"                                                            included in conveying the object code work.\n"
"\n"
"                                                            A \"User Product\" is either (1) a \"consumer\n"
"                                                            product\", which means any\n"
"                                                            tangible personal property which is normally used for\n"
"                                                            personal, family,\n"
"                                                            or household purposes, or (2) anything designed or sold for\n"
"                                                            incorporation\n"
"                                                            into a dwelling. In determining whether a product is a\n"
"                                                            consumer product,\n"
"                                                            doubtful cases shall be resolved in favor of coverage. For a\n"
"                                                            particular\n"
"                                                            product received by a particular user, \"normally used\"\n"
"                                                            refers to a\n"
"                                                            typical or common use of that class of product, regardless\n"
"                                                            of the status\n"
"                                                            of the particular user or of the way in which the particular\n"
"                                                            user\n"
"                                                            actually uses, or expects or is expected to use, the\n"
"                                                            product. A product\n"
"                                                            is a consumer product regardless of whether the product has\n"
"                                                            substantial\n"
"                                                            commercial, industrial or non-consumer uses, unless such\n"
"                                                            uses represent\n"
"                                                            the only significant mode of use of the product.\n"
"\n"
"                                                            \"Installation Information\" for a User Product\n"
"                                                            means any methods,\n"
"                                                            procedures, authorization keys, or other information\n"
"                                                            required to install\n"
"                                                            and execute modified versions of a covered work in that User\n"
"                                                            Product from\n"
"                                                            a modified version of its Corresponding Source. The\n"
"                                                            information must\n"
"                                                            suffice to ensure that the continued functioning of the\n"
"                                                            modified object\n"
"                                                            code is in no case prevented or interfered with solely\n"
"                                                            because\n"
"                                                            modification has been made.\n"
"\n"
"                                                            If you convey an object code work under this section in, or\n"
"                                                            with, or\n"
"                                                            specifically for use in, a User Product, and the conveying\n"
"                                                            occurs as\n"
"                                                            part of a transaction in which the right of possession and\n"
"                                                            use of the\n"
"                                                            User Product is transferred to the recipient in perpetuity\n"
"                                                            or for a\n"
"                                                            fixed term (regardless of how the transaction is\n"
"                                                            characterized), the\n"
"                                                            Corresponding Source conveyed under this section must be\n"
"                                                            accompanied\n"
"                                                            by the Installation Information. But this requirement does\n"
"                                                            not apply\n"
"                                                            if neither you nor any third party retains the ability to\n"
"                                                            install\n"
"                                                            modified object code on the User Product (for example, the\n"
"                                                            work has\n"
"                                                            been installed in ROM).\n"
"\n"
"                                                            The requirement to provide Installation Information does not\n"
"                                                            include a\n"
"                                                            requirement to continue to provide support service,\n"
"                                                            warranty, or updates\n"
"                                                            for a work that has been modified or installed by the\n"
"                                                            recipient, or for\n"
"                                                            the User Product in which it has been modified or installed.\n"
"                                                            Access to a\n"
"                                                            network may be denied when the modification itself\n"
"                                                            materially and\n"
"                                                            adversely affects the operation of the network or violates\n"
"                                                            the rules and\n"
"                                                            protocols for communication across the network.\n"
"\n"
"                                                            Corresponding Source conveyed, and Installation Information\n"
"                                                            provided,\n"
"                                                            in accord with this section must be in a format that is\n"
"                                                            publicly\n"
"                                                            documented (and with an implementation available to the\n"
"                                                            public in\n"
"                                                            source code form), and must require no special password or\n"
"                                                            key for\n"
"                                                            unpacking, reading or copying.\n"
"\n"
"                                                            7. Additional Terms.\n"
"\n"
"                                                            \"Additional permissions\" are terms that supplement\n"
"                                                            the terms of this\n"
"                                                            License by making exceptions from one or more of its\n"
"                                                            conditions.\n"
"                                                            Additional permissions that are applicable to the entire\n"
"                                                            Program shall\n"
"                                                            be treated as though they were included in this License, to\n"
"                                                            the extent\n"
"                                                            that they are valid under applicable law. If additional\n"
"                                                            permissions\n"
"                                                            apply only to part of the Program, that part may be used\n"
"                                                            separately\n"
"                                                            under those permissions, but the entire Program remains\n"
"                                                            governed by\n"
"                                                            this License without regard to the additional permissions.\n"
"\n"
"                                                            When you convey a copy of a covered work, you may at your\n"
"                                                            option\n"
"                                                            remove any additional permissions from that copy, or from\n"
"                                                            any part of\n"
"                                                            it. (Additional permissions may be written to require their\n"
"                                                            own\n"
"                                                            removal in certain cases when you modify the work.) You may\n"
"                                                            place\n"
"                                                            additional permissions on material, added by you to a\n"
"                                                            covered work,\n"
"                                                            for which you have or can give appropriate copyright\n"
"                                                            permission.\n"
"\n"
"                                                            Notwithstanding any other provision of this License, for\n"
"                                                            material you\n"
"                                                            add to a covered work, you may (if authorized by the\n"
"                                                            copyright holders of\n"
"                                                            that material) supplement the terms of this License with\n"
"                                                            terms:\n"
"\n"
"                                                            a) Disclaiming warranty or limiting liability differently\n"
"                                                            from the\n"
"                                                            terms of sections 15 and 16 of this License; or\n"
"\n"
"                                                            b) Requiring preservation of specified reasonable legal\n"
"                                                            notices or\n"
"                                                            author attributions in that material or in the Appropriate\n"
"                                                            Legal\n"
"                                                            Notices displayed by works containing it; or\n"
"\n"
"                                                            c) Prohibiting misrepresentation of the origin of that\n"
"                                                            material, or\n"
"                                                            requiring that modified versions of such material be marked\n"
"                                                            in\n"
"                                                            reasonable ways as different from the original version; or\n"
"\n"
"                                                            d) Limiting the use for publicity purposes of names of\n"
"                                                            licensors or\n"
"                                                            authors of the material; or\n"
"\n"
"                                                            e) Declining to grant rights under trademark law for use of\n"
"                                                            some\n"
"                                                            trade names, trademarks, or service marks; or\n"
"\n"
"                                                            f) Requiring indemnification of licensors and authors of\n"
"                                                            that\n"
"                                                            material by anyone who conveys the material (or modified\n"
"                                                            versions of\n"
"                                                            it) with contractual assumptions of liability to the\n"
"                                                            recipient, for\n"
"                                                            any liability that these contractual assumptions directly\n"
"                                                            impose on\n"
"                                                            those licensors and authors.\n"
"\n"
"                                                            All other non-permissive additional terms are considered\n"
"                                                            \"further\n"
"                                                            restrictions\" within the meaning of section 10. If the\n"
"                                                            Program as you\n"
"                                                            received it, or any part of it, contains a notice stating\n"
"                                                            that it is\n"
"                                                            governed by this License along with a term that is a further\n"
"                                                            restriction, you may remove that term. If a license document\n"
"                                                            contains\n"
"                                                            a further restriction but permits relicensing or conveying\n"
"                                                            under this\n"
"                                                            License, you may add to a covered work material governed by\n"
"                                                            the terms\n"
"                                                            of that license document, provided that the further\n"
"                                                            restriction does\n"
"                                                            not survive such relicensing or conveying.\n"
"\n"
"                                                            If you add terms to a covered work in accord with this\n"
"                                                            section, you\n"
"                                                            must place, in the relevant source files, a statement of the\n"
"                                                            additional terms that apply to those files, or a notice\n"
"                                                            indicating\n"
"                                                            where to find the applicable terms.\n"
"\n"
"                                                            Additional terms, permissive or non-permissive, may be\n"
"                                                            stated in the\n"
"                                                            form of a separately written license, or stated as\n"
"                                                            exceptions;\n"
"                                                            the above requirements apply either way.\n"
"\n"
"                                                            8. Termination.\n"
"\n"
"                                                            You may not propagate or modify a covered work except as\n"
"                                                            expressly\n"
"                                                            provided under this License. Any attempt otherwise to\n"
"                                                            propagate or\n"
"                                                            modify it is void, and will automatically terminate your\n"
"                                                            rights under\n"
"                                                            this License (including any patent licenses granted under\n"
"                                                            the third\n"
"                                                            paragraph of section 11).\n"
"\n"
"                                                            However, if you cease all violation of this License, then\n"
"                                                            your\n"
"                                                            license from a particular copyright holder is reinstated (a)\n"
"                                                            provisionally, unless and until the copyright holder\n"
"                                                            explicitly and\n"
"                                                            finally terminates your license, and (b) permanently, if the\n"
"                                                            copyright\n"
"                                                            holder fails to notify you of the violation by some\n"
"                                                            reasonable means\n"
"                                                            prior to 60 days after the cessation.\n"
"\n"
"                                                            Moreover, your license from a particular copyright holder is\n"
"                                                            reinstated permanently if the copyright holder notifies you\n"
"                                                            of the\n"
"                                                            violation by some reasonable means, this is the first time\n"
"                                                            you have\n"
"                                                            received notice of violation of this License (for any work)\n"
"                                                            from that\n"
"                                                            copyright holder, and you cure the violation prior to 30\n"
"                                                            days after\n"
"                                                            your receipt of the notice.\n"
"\n"
"                                                            Termination of your rights under this section does not\n"
"                                                            terminate the\n"
"                                                            licenses of parties who have received copies or rights from\n"
"                                                            you under\n"
"                                                            this License. If your rights have been terminated and not\n"
"                                                            permanently\n"
"                                                            reinstated, you do not qualify to receive new licenses for\n"
"                                                            the same\n"
"                                                            material under section 10.\n"
"\n"
"                                                            9. Acceptance Not Required for Having Copies.\n"
"\n"
"                                                            You are not required to accept this License in order to\n"
"                                                            receive or\n"
"                                                            run a copy of the Program. Ancillary propagation of a\n"
"                                                            covered work\n"
"                                                            occurring solely as a consequence of using peer-to-peer\n"
"                                                            transmission\n"
"                                                            to receive a copy likewise does not require acceptance.\n"
"                                                            However,\n"
"                                                            nothing other than this License grants you permission to\n"
"                                                            propagate or\n"
"                                                            modify any covered work. These actions infringe copyright if\n"
"                                                            you do\n"
"                                                            not accept this License. Therefore, by modifying or\n"
"                                                            propagating a\n"
"                                                            covered work, you indicate your acceptance of this License\n"
"                                                            to do so.\n"
"\n"
"                                                            10. Automatic Licensing of Downstream Recipients.\n"
"\n"
"                                                            Each time you convey a covered work, the recipient\n"
"                                                            automatically\n"
"                                                            receives a license from the original licensors, to run,\n"
"                                                            modify and\n"
"                                                            propagate that work, subject to this License. You are not\n"
"                                                            responsible\n"
"                                                            for enforcing compliance by third parties with this License.\n"
"\n"
"                                                            An \"entity transaction\" is a transaction\n"
"                                                            transferring control of an\n"
"                                                            organization, or substantially all assets of one, or\n"
"                                                            subdividing an\n"
"                                                            organization, or merging organizations. If propagation of a\n"
"                                                            covered\n"
"                                                            work results from an entity transaction, each party to that\n"
"                                                            transaction who receives a copy of the work also receives\n"
"                                                            whatever\n"
"                                                            licenses to the work the party\'s predecessor in interest had\n"
"                                                            or could\n"
"                                                            give under the previous paragraph, plus a right to\n"
"                                                            possession of the\n"
"                                                            Corresponding Source of the work from the predecessor in\n"
"                                                            interest, if\n"
"                                                            the predecessor has it or can get it with reasonable\n"
"                                                            efforts.\n"
"\n"
"                                                            You may not impose any further restrictions on the exercise\n"
"                                                            of the\n"
"                                                            rights granted or affirmed under this License. For example,\n"
"                                                            you may\n"
"                                                            not impose a license fee, royalty, or other charge for\n"
"                                                            exercise of\n"
"                                                            rights granted under this License, and you may not initiate\n"
"                                                            litigation\n"
"                                                            (including a cross-claim or counterclaim in a lawsuit)\n"
"                                                            alleging that\n"
"                                                            any patent claim is infringed by making, using, selling,\n"
"                                                            offering for\n"
"                                                            sale, or importing the Program or any portion of it.\n"
"\n"
"                                                            11. Patents.\n"
"\n"
"                                                            A \"contributor\" is a copyright holder who\n"
"                                                            authorizes use under this\n"
"                                                            License of the Program or a work on which the Program is\n"
"                                                            based. The\n"
"                                                            work thus licensed is called the contributor\'s \"contributor\n"
"                                                            version\".\n"
"\n"
"                                                            A contributor\'s \"essential patent claims\" are all\n"
"                                                            patent claims\n"
"                                                            owned or controlled by the contributor, whether already\n"
"                                                            acquired or\n"
"                                                            hereafter acquired, that would be infringed by some manner,\n"
"                                                            permitted\n"
"                                                            by this License, of making, using, or selling its\n"
"                                                            contributor version,\n"
"                                                            but do not include claims that would be infringed only as a\n"
"                                                            consequence of further modification of the contributor\n"
"                                                            version. For\n"
"                                                            purposes of this definition, \"control\" includes\n"
"                                                            the right to grant\n"
"                                                            patent sublicenses in a manner consistent with the\n"
"                                                            requirements of\n"
"                                                            this License.\n"
"\n"
"                                                            Each contributor grants you a non-exclusive, worldwide,\n"
"                                                            royalty-free\n"
"                                                            patent license under the contributor\'s essential patent\n"
"                                                            claims, to\n"
"                                                            make, use, sell, offer for sale, import and otherwise run,\n"
"                                                            modify and\n"
"                                                            propagate the contents of its contributor version.\n"
"\n"
"                                                            In the following three paragraphs, a \"patent license\"\n"
"                                                            is any express\n"
"                                                            agreement or commitment, however denominated, not to enforce\n"
"                                                            a patent\n"
"                                                            (such as an express permission to practice a patent or\n"
"                                                            covenant not to\n"
"                                                            sue for patent infringement). To \"grant\" such a\n"
"                                                            patent license to a\n"
"                                                            party means to make such an agreement or commitment not to\n"
"                                                            enforce a\n"
"                                                            patent against the party.\n"
"\n"
"                                                            If you convey a covered work, knowingly relying on a patent\n"
"                                                            license,\n"
"                                                            and the Corresponding Source of the work is not available\n"
"                                                            for anyone\n"
"                                                            to copy, free of charge and under the terms of this License,\n"
"                                                            through a\n"
"                                                            publicly available network server or other readily\n"
"                                                            accessible means,\n"
"                                                            then you must either (1) cause the Corresponding Source to\n"
"                                                            be so\n"
"                                                            available, or (2) arrange to deprive yourself of the benefit\n"
"                                                            of the\n"
"                                                            patent license for this particular work, or (3) arrange, in\n"
"                                                            a manner\n"
"                                                            consistent with the requirements of this License, to extend\n"
"                                                            the patent\n"
"                                                            license to downstream recipients. \"Knowingly relying\"\n"
"                                                            means you have\n"
"                                                            actual knowledge that, but for the patent license, your\n"
"                                                            conveying the\n"
"                                                            covered work in a country, or your recipient\'s use of the\n"
"                                                            covered work\n"
"                                                            in a country, would infringe one or more identifiable\n"
"                                                            patents in that\n"
"                                                            country that you have reason to believe are valid.\n"
"\n"
"                                                            If, pursuant to or in connection with a single transaction\n"
"                                                            or\n"
"                                                            arrangement, you convey, or propagate by procuring\n"
"                                                            conveyance of, a\n"
"                                                            covered work, and grant a patent license to some of the\n"
"                                                            parties\n"
"                                                            receiving the covered work authorizing them to use,\n"
"                                                            propagate, modify\n"
"                                                            or convey a specific copy of the covered work, then the\n"
"                                                            patent license\n"
"                                                            you grant is automatically extended to all recipients of the\n"
"                                                            covered\n"
"                                                            work and works based on it.\n"
"\n"
"                                                            A patent license is \"discriminatory\" if it does\n"
"                                                            not include within\n"
"                                                            the scope of its coverage, prohibits the exercise of, or is\n"
"                                                            conditioned on the non-exercise of one or more of the rights\n"
"                                                            that are\n"
"                                                            specifically granted under this License. You may not convey\n"
"                                                            a covered\n"
"                                                            work if you are a party to an arrangement with a third party\n"
"                                                            that is\n"
"                                                            in the business of distributing software, under which you\n"
"                                                            make payment\n"
"                                                            to the third party based on the extent of your activity of\n"
"                                                            conveying\n"
"                                                            the work, and under which the third party grants, to any of\n"
"                                                            the\n"
"                                                            parties who would receive the covered work from you, a\n"
"                                                            discriminatory\n"
"                                                            patent license (a) in connection with copies of the covered\n"
"                                                            work\n"
"                                                            conveyed by you (or copies made from those copies), or (b)\n"
"                                                            primarily\n"
"                                                            for and in connection with specific products or compilations\n"
"                                                            that\n"
"                                                            contain the covered work, unless you entered into that\n"
"                                                            arrangement,\n"
"                                                            or that patent license was granted, prior to 28 March 2007.\n"
"\n"
"                                                            Nothing in this License shall be construed as excluding or\n"
"                                                            limiting\n"
"                                                            any implied license or other defenses to infringement that\n"
"                                                            may\n"
"                                                            otherwise be available to you under applicable patent law.\n"
"\n"
"                                                            12. No Surrender of Others\' Freedom.\n"
"\n"
"                                                            If conditions are imposed on you (whether by court order,\n"
"                                                            agreement or\n"
"                                                            otherwise) that contradict the conditions of this License,\n"
"                                                            they do not\n"
"                                                            excuse you from the conditions of this License. If you\n"
"                                                            cannot convey a\n"
"                                                            covered work so as to satisfy simultaneously your\n"
"                                                            obligations under this\n"
"                                                            License and any other pertinent obligations, then as a\n"
"                                                            consequence you may\n"
"                                                            not convey it at all. For example, if you agree to terms\n"
"                                                            that obligate you\n"
"                                                            to collect a royalty for further conveying from those to\n"
"                                                            whom you convey\n"
"                                                            the Program, the only way you could satisfy both those terms\n"
"                                                            and this\n"
"                                                            License would be to refrain entirely from conveying the\n"
"                                                            Program.\n"
"\n"
"                                                            13. Use with the GNU Affero General Public License.\n"
"\n"
"                                                            Notwithstanding any other provision of this License, you\n"
"                                                            have\n"
"                                                            permission to link or combine any covered work with a work\n"
"                                                            licensed\n"
"                                                            under version 3 of the GNU Affero General Public License\n"
"                                                            into a single\n"
"                                                            combined work, and to convey the resulting work. The terms\n"
"                                                            of this\n"
"                                                            License will continue to apply to the part which is the\n"
"                                                            covered work,\n"
"                                                            but the special requirements of the GNU Affero General\n"
"                                                            Public License,\n"
"                                                            section 13, concerning interaction through a network will\n"
"                                                            apply to the\n"
"                                                            combination as such.\n"
"\n"
"                                                            14. Revised Versions of this License.\n"
"\n"
"                                                            The Free Software Foundation may publish revised and/or new\n"
"                                                            versions of\n"
"                                                            the GNU General Public License from time to time. Such new\n"
"                                                            versions will\n"
"                                                            be similar in spirit to the present version, but may differ\n"
"                                                            in detail to\n"
"                                                            address new problems or concerns.\n"
"\n"
"                                                            Each version is given a distinguishing version number. If\n"
"                                                            the\n"
"                                                            Program specifies that a certain numbered version of the GNU\n"
"                                                            General\n"
"                                                            Public License \"or any later version\" applies to\n"
"                                                            it, you have the\n"
"                                                            option of following the terms and conditions either of that\n"
"                                                            numbered\n"
"                                                            version or of any later version published by the Free\n"
"                                                            Software\n"
"                                                            Foundation. If the Program does not specify a version number\n"
"                                                            of the\n"
"                                                            GNU General Public License, you may choose any version ever\n"
"                                                            published\n"
"                                                            by the Free Software Foundation.\n"
"\n"
"                                                            If the Program specifies that a proxy can decide which\n"
"                                                            future\n"
"                                                            versions of the GNU General Public License can be used, that\n"
"                                                            proxy\'s\n"
"                                                            public statement of acceptance of a version permanently\n"
"                                                            authorizes you\n"
"                                                            to choose that version for the Program.\n"
"\n"
"                                                            Later license versions may give you additional or different\n"
"                                                            permissions. However, no additional obligations are imposed\n"
"                                                            on any\n"
"                                                            author or copyright holder as a result of your choosing to\n"
"                                                            follow a\n"
"                                                            later version.\n"
"\n"
"                                                            15. Disclaimer of Warranty.\n"
"\n"
"                                                            THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT\n"
"                                                            PERMITTED BY\n"
"                                                            APPLICABLE LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE\n"
"                                                            COPYRIGHT\n"
"                                                            HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM \"AS IS\"\n"
"                                                            WITHOUT WARRANTY\n"
"                                                            OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT\n"
"                                                            LIMITED TO,\n"
"                                                            THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A\n"
"                                                            PARTICULAR\n"
"                                                            PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE\n"
"                                                            OF THE PROGRAM\n"
"                                                            IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME\n"
"                                                            THE COST OF\n"
"                                                            ALL NECESSARY SERVICING, REPAIR OR CORRECTION.\n"
"\n"
"                                                            16. Limitation of Liability.\n"
"\n"
"                                                            IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO\n"
"                                                            IN WRITING\n"
"                                                            WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES\n"
"                                                            AND/OR CONVEYS\n"
"                                                            THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR\n"
"                                                            DAMAGES, INCLUDING ANY\n"
"                                                            GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES\n"
"                                                            ARISING OUT OF THE\n"
"                                                            USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT\n"
"                                                            LIMITED TO LOSS OF\n"
"                                                            DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED\n"
"                                                            BY YOU OR THIRD\n"
"                                                            PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY\n"
"                                                            OTHER PROGRAMS),\n"
"                                                            EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE\n"
"                                                            POSSIBILITY OF\n"
"                                                            SUCH DAMAGES.\n"
"\n"
"                                                            17. Interpretation of Sections 15 and 16.\n"
"\n"
"                                                            If the disclaimer of warranty and limitation of liability\n"
"                                                            provided\n"
"                                                            above cannot be given local legal effect according to their\n"
"                                                            te\n"
"                                                        "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Licencia"))
        self.pushButtonClose.setText(_translate("Dialog", "Cerrar"))


import fatcow_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
