# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/descarga_completa.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(561, 391)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Iconos/Icons/fatcow/Principal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.gridLayout.addWidget(self.widget_2, 4, 0, 1, 2)
        self.lineTitulo = QtWidgets.QLineEdit(Dialog)
        self.lineTitulo.setObjectName("lineTitulo")
        self.gridLayout.addWidget(self.lineTitulo, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BoxTemporada = QtWidgets.QComboBox(Dialog)
        self.BoxTemporada.setObjectName("BoxTemporada")
        self.horizontalLayout_2.addWidget(self.BoxTemporada)
        self.lineTemp = QtWidgets.QLineEdit(Dialog)
        self.lineTemp.setEnabled(True)
        self.lineTemp.setObjectName("lineTemp")
        self.horizontalLayout_2.addWidget(self.lineTemp, 0, QtCore.Qt.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(350, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.BoxCapitulos = QtWidgets.QComboBox(Dialog)
        self.BoxCapitulos.setObjectName("BoxCapitulos")
        self.horizontalLayout_4.addWidget(self.BoxCapitulos)
        self.lineCap = QtWidgets.QLineEdit(Dialog)
        self.lineCap.setEnabled(True)
        self.lineCap.setObjectName("lineCap")
        self.horizontalLayout_4.addWidget(self.lineCap)
        spacerItem1 = QtWidgets.QSpacerItem(350, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBoxTg = QtWidgets.QCheckBox(self.widget)
        self.checkBoxTg.setObjectName("checkBoxTg")
        self.horizontalLayout_6.addWidget(self.checkBoxTg, 0, QtCore.Qt.AlignLeft)
        self.gridLayout.addWidget(self.widget, 3, 1, 1, 1)
        self.WidgetBotones = QtWidgets.QWidget(Dialog)
        self.WidgetBotones.setObjectName("WidgetBotones")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.WidgetBotones)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.progressBar = QtWidgets.QProgressBar(self.WidgetBotones)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)
        self.widget_4 = QtWidgets.QWidget(self.WidgetBotones)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButtonAplicar = QtWidgets.QPushButton(self.widget_4)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Iconos/Icons/fatcow/file_save_as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAplicar.setIcon(icon1)
        self.pushButtonAplicar.setObjectName("pushButtonAplicar")
        self.horizontalLayout_5.addWidget(self.pushButtonAplicar)
        self.pushButtonCerrar = QtWidgets.QPushButton(self.widget_4)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Iconos/Icons/fatcow/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonCerrar.setIcon(icon2)
        self.pushButtonCerrar.setObjectName("pushButtonCerrar")
        self.horizontalLayout_5.addWidget(self.pushButtonCerrar)
        self.horizontalLayout_3.addWidget(self.widget_4)
        self.gridLayout.addWidget(self.WidgetBotones, 5, 0, 1, 2)
        self.widget_2.raise_()
        self.label_5.raise_()
        self.lineTitulo.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.widget.raise_()
        self.label.setBuddy(self.lineTitulo)

        self.retranslateUi(Dialog)
        self.BoxTemporada.activated['QString'].connect(self.lineTemp.setText)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Descargar Serie Completa"))
        self.label.setText(_translate("Dialog", "Titulo"))
        self.label_5.setText(_translate("Dialog", "Temporada"))
        self.label_2.setText(_translate("Dialog", "Capitulos:"))
        self.label_3.setText(_translate("Dialog", "Telegram"))
        self.checkBoxTg.setText(_translate("Dialog", "Enviar"))
        self.pushButtonAplicar.setText(_translate("Dialog", "Descargar"))
        self.pushButtonCerrar.setText(_translate("Dialog", "Cerrar"))


import app.views.ui.fatcow_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
